config:
  credentials: []
  project_repos:
    github.com/013k-m/python-pytest-example:
      branch: master
      repo: https://github.com/013k-m/python-pytest-example
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-amber-sloth.sh
        container: qc.acc_lovely-heliotrope-binturong
  QC.Doc:
    repos:
      github.com/013k-m/python-pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-dandelion-rat.sh
        container: qc.doc_pasty-ruby-penguin
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cinnabar-ant.sh
        container: qc.doc_squeaky-persimmon-greyhound
      github.com/013k-m/python-pytest-example markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cobalt-shrew.sh
        container: qc.doc_boozy-magnolia-insect
  QC.Lic:
    repos:
      github.com/013k-m/python-pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-turquoise-oyster.sh
        container: qc.lic_snappy-red-capybara
  QC.Sec:
    repos:
      github.com/013k-m/python-pytest-example bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-burgundy-neanderthal.sh
        container: qc.sec_blurry-myrtle-chamois
  QC.Sty:
    repos:
      github.com/013k-m/python-pytest-example flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-plum-bonobo.sh
        container: qc.sty_wheezy-xanthic-dachsbracke
  QC.Uni:
    repos:
      github.com/013k-m/python-pytest-example commands:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-teal-dragonfly.sh
        container: qc.uni_dorky-buff-wallaby
  QC.Ver:
    repos:
      github.com/013k-m/python-pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-brass-nightingale.sh
        container: qc.ver_snazzy-apricot-chimpanzee
timeout: 5400
