config:
  credentials: []
  project_repos:
    github.com/013k-m/python-pytest-example:
      branch: master
      repo: https://github.com/013k-m/python-pytest-example
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-viridian-moose.sh
        container: qc.acc_stinky-chocolate-lemming
  QC.Doc:
    repos:
      github.com/013k-m/python-pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-salmon-crab.sh
        container: qc.doc_baggy-pumpkin-zonkey
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-periwinkle-rottweiler.sh
        container: qc.doc_chewy-cobalt-numbat
      github.com/013k-m/python-pytest-example markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-scarlet-hyrax.sh
        container: qc.doc_blurry-rose-rattlesnake
  QC.Lic:
    repos:
      github.com/013k-m/python-pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-auburn-caterpillar.sh
        container: qc.lic_ugly-firebrick-collie
  QC.Sec:
    repos:
      github.com/013k-m/python-pytest-example bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-white-yak.sh
        container: qc.sec_gummy-maroon-dachsbracke
  QC.Sty:
    repos:
      github.com/013k-m/python-pytest-example flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-auburn-eagle.sh
        container: qc.sty_snippy-mustard-fowl
  QC.Uni:
    repos:
      github.com/013k-m/python-pytest-example commands:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-asparagus-fish.sh
        container: qc.uni_cozy-pink-crocodile
  QC.Ver:
    repos:
      github.com/013k-m/python-pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-green-cattle.sh
        container: qc.ver_pasty-myrtle-spoonbill
timeout: 5400
