config:
  credentials: []
  project_repos:
    github.com/013k-m/python-pytest-example:
      branch: master
      repo: https://github.com/013k-m/python-pytest-example
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-spec:
      branch: master
      repo: https://github.com/eosc-synergy/sqaaas-api-spec
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cinnamon-coati.sh
        container: qc.acc_slaphappy-russet-setter
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-spec find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-maroon-spaniel.sh
        container: qc.doc_wimpy-magnolia-rat
      github.com/eosc-synergy/sqaaas-api-spec git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-orange-burmese.sh
        container: qc.doc_geeky-chartreuse-pinscher
  QC.Lic:
    repos:
      github.com/013k-m/python-pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-champagne-wombat.sh
        container: qc.lic_goopy-eggplant-buffalo
  QC.Ver:
    repos:
      github.com/013k-m/python-pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-red-sloth.sh
        container: qc.ver_hilly-cream-quoll
timeout: 5400
