config:
  credentials: []
  project_repos:
    github.com/013k-m/python-pytest-example:
      branch: master
      repo: https://github.com/013k-m/python-pytest-example
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cerulean-elephant.sh
        container: qc.acc_bluesy-lemon-oriole
  QC.Doc:
    repos:
      github.com/013k-m/python-pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-seashell-gharial.sh
        container: qc.doc_homey-amethyst-crane
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-buff-bat.sh
        container: qc.doc_blurry-ultramarine-cow
      github.com/013k-m/python-pytest-example markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-tangerine-warthog.sh
        container: qc.doc_muzzy-brass-tetra
  QC.Lic:
    repos:
      github.com/013k-m/python-pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-wisteria-terrier.sh
        container: qc.lic_fuzzy-magenta-okapi
  QC.Sec:
    repos:
      github.com/013k-m/python-pytest-example bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-tomato-spaniel.sh
        container: qc.sec_beady-red-bulldog
  QC.Sty:
    repos:
      github.com/013k-m/python-pytest-example flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-tan-whale.sh
        container: qc.sty_paltry-silver-newfoundland
  QC.Uni:
    repos:
      github.com/013k-m/python-pytest-example commands:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-maroon-antelope.sh
        container: qc.uni_sloppy-apricot-audemer
  QC.Ver:
    repos:
      github.com/013k-m/python-pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-burgundy-caiman.sh
        container: qc.ver_lovely-alizarin-dachsbracke
timeout: 5400
