config:
  credentials: []
  project_repos:
    github.com/013k-m/python-pytest-example:
      branch: master
      repo: https://github.com/013k-m/python-pytest-example
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lavender-dingo.sh
        container: qc.acc_greasy-violet-squid
  QC.Doc:
    repos:
      github.com/013k-m/python-pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-chocolate-lemur.sh
        container: qc.doc_foggy-orange-moth
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-maroon-chicken.sh
        container: qc.doc_cheeky-pear-goat
  QC.Lic:
    repos:
      github.com/013k-m/python-pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cardinal-chamois.sh
        container: qc.lic_cozy-buff-zorse
  QC.Ver:
    repos:
      github.com/013k-m/python-pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cardinal-mist.sh
        container: qc.ver_chummy-viridian-burmese
timeout: 5400
