config:
  credentials: []
  project_repos:
    github.com/013k-m/python-pytest-example:
      branch: master
      repo: https://github.com/013k-m/python-pytest-example
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-jade-shrimp.sh
        container: qc.acc_scanty-cyan-numbat
  QC.Doc:
    repos:
      github.com/013k-m/python-pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-rust-dog.sh
        container: qc.doc_cheeky-heliotrope-tiger
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-black-fowl.sh
        container: qc.doc_shaggy-vermilion-lemur
      github.com/013k-m/python-pytest-example markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-rose-angora.sh
        container: qc.doc_stinky-saffron-dingo
  QC.Lic:
    repos:
      github.com/013k-m/python-pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-burgundy-rattlesnake.sh
        container: qc.lic_scanty-azure-corgi
  QC.Sec:
    repos:
      github.com/013k-m/python-pytest-example bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-salmon-monkey.sh
        container: qc.sec_cozy-harlequin-chin
  QC.Sty:
    repos:
      github.com/013k-m/python-pytest-example flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-celadon-lizard.sh
        container: qc.sty_sunny-platinum-mule
  QC.Uni:
    repos:
      github.com/013k-m/python-pytest-example commands:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-bronze-gecko.sh
        container: qc.uni_hazy-xanthic-lynx
  QC.Ver:
    repos:
      github.com/013k-m/python-pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-olive-oyster.sh
        container: qc.ver_foggy-champagne-wasp
timeout: 5400
