config:
  credentials: []
  project_repos:
    github.com/013k-m/python-pytest-example:
      branch: master
      repo: https://github.com/013k-m/python-pytest-example
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-harlequin-stingray.sh
        container: qc.acc_freaky-peach-balinese
  QC.Doc:
    repos:
      github.com/013k-m/python-pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ruby-reindeer.sh
        container: qc.doc_snippy-tan-foxhound
      github.com/013k-m/python-pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ultramarine-rottweiler.sh
        container: qc.doc_grumpy-buff-pig
      github.com/013k-m/python-pytest-example markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-tan-dog.sh
        container: qc.doc_gamy-charcoal-dogfish
  QC.Lic:
    repos:
      github.com/013k-m/python-pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-sangria-mole.sh
        container: qc.lic_paltry-orange-walrus
  QC.Sec:
    repos:
      github.com/013k-m/python-pytest-example bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-linen-hedgehog.sh
        container: qc.sec_dorky-wisteria-giraffe
  QC.Sty:
    repos:
      github.com/013k-m/python-pytest-example flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-auburn-bulldog.sh
        container: qc.sty_ready-alizarin-reindeer
  QC.Uni:
    repos:
      github.com/013k-m/python-pytest-example pytest:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-jade-tapir.sh
        container: qc.uni_wheezy-lemon-catfish
  QC.Ver:
    repos:
      github.com/013k-m/python-pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-fuchsia-wombat.sh
        container: qc.ver_snappy-carmine-woodlouse
timeout: 5400
